spring.datasource.url=jdbc:mysql://localhost:3306/acervo_museu
spring.datasource.username=root
spring.datasource.password=SUA_SENHA_AQUI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
