spring.application.name=MuseuTreze
#Update the database schema based on the entities create-drop / update
spring.jpa.hibernate.ddl-auto= update
#create database if not exists mysql true spring boot
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/MuseuTreze?createDatabaseIfNotExist=true}
#DB User
spring.datasource.username=${DB_USERNAME:root}
#DB password
spring.datasource.password=${DB_PASSWORD:1234}
